# charlib character panel  (3D Viewport > Sidebar (N) > "Character" tab)
# Generated by charlib. Object / material names are read from scene properties set at build time.
#
#  Expression : the mood (eyes / brows / mouth).  Timeline markers "expr:<name>" switch it during playback.
#  Talking    : a separate mouth layer drawn on top of ANY expression (happy-talking, sad-talking, ...).
#               "Mouth" is keyframable: 0 = the expression's own mouth, A I U E O = open shapes.
#               - Auto Talk     : fills the frame range with natural-looking random mouth movement
#               - Lip-sync Audio: reads a voice file (wav/mp3, e.g. TTS output) and keys the mouth to its loudness
#  Action     : body movement (includes Talk_* loops made for dialogue).
import bpy, random

MOODS = ['neutral', 'smile', 'happy', 'sad', 'angry', 'surprised', 'shy', 'crying', 'eyes_closed', 'wink']
MOUTHS = ['(expression)', 'A', 'I', 'U', 'E', 'O']
def _cfg(key, default):
    return bpy.context.scene.get(key, default) if bpy.context.scene else default


class _Names:
    @property
    def MAT(self): return _cfg('charlib_mat', 'Material_1')
    @property
    def RIG(self): return _cfg('charlib_rig', 'Character_Rig')
    @property
    def TITLE(self): return _cfg('charlib_name', 'Character')


_N = _Names()


# ---------------------------------------------------------------- images / material
def _img(key, colorspace=None):
    im = bpy.data.images.get(key)
    if im is None:
        import os
        ext = 'png' if key == 'mouth_mask' else 'jpg'
        rel = '//textures/%s.%s' % (key, ext)
        if not os.path.exists(bpy.path.abspath(rel)):
            return _img('face_neutral') if key != 'face_neutral' else None
        im = bpy.data.images.load(bpy.path.abspath(rel), check_existing=True)
        im.name = key
        im.filepath = rel          # keep the path relative so the library folder can be moved
    if colorspace:
        im.colorspace_settings.name = colorspace
    return im


def ensure_nodes():
    nt = bpy.data.materials[_N.MAT].node_tree
    N = nt.nodes
    if 'FaceMood' in N:
        return nt
    tex = [n for n in N if n.type == 'TEX_IMAGE']
    mood = tex[0]; mood.name = mood.label = 'FaceMood'
    for t in tex[1:]:
        N.remove(t)
    bsdf = [n for n in N if n.type == 'BSDF_PRINCIPLED'][0]
    mouth = N.new('ShaderNodeTexImage'); mouth.name = mouth.label = 'FaceMouth'; mouth.image = _img('face_mouth_A')
    mask = N.new('ShaderNodeTexImage'); mask.name = mask.label = 'MouthMask'; mask.image = _img('mouth_mask', 'Non-Color')
    on = N.new('ShaderNodeValue'); on.name = on.label = 'MouthOn'; on.outputs[0].default_value = 0.0
    mul = N.new('ShaderNodeMath'); mul.operation = 'MULTIPLY'; mul.name = 'MouthFac'
    mix = N.new('ShaderNodeMix'); mix.data_type = 'RGBA'; mix.name = 'FaceMix'
    nt.links.new(mask.outputs['Color'], mul.inputs[0]); nt.links.new(on.outputs[0], mul.inputs[1])
    nt.links.new(mul.outputs[0], mix.inputs['Factor'])
    nt.links.new(mood.outputs['Color'], mix.inputs[6]); nt.links.new(mouth.outputs['Color'], mix.inputs[7])
    nt.links.new(mix.outputs[2], bsdf.inputs['Base Color'])
    nt.links.new(mix.outputs[2], bsdf.inputs['Emission Color'])
    for i, n in enumerate((mood, mouth, mask, on, mul, mix)):
        n.location = (-900 + 250 * (i // 3), 300 - 300 * (i % 3))
    return nt


def set_expression(name):
    nt = ensure_nodes()
    im = _img('face_' + name)
    if nt.nodes['FaceMood'].image != im:
        nt.nodes['FaceMood'].image = im


def set_mouth(idx):
    nt = ensure_nodes()
    idx = max(0, min(int(idx), len(MOUTHS) - 1))
    on = nt.nodes['MouthOn'].outputs[0]
    if idx == 0:
        if on.default_value != 0.0: on.default_value = 0.0
        return
    im = _img('face_mouth_' + MOUTHS[idx])
    if nt.nodes['FaceMouth'].image != im:
        nt.nodes['FaceMouth'].image = im
    if on.default_value != 1.0: on.default_value = 1.0


def set_action(name):
    arm = bpy.data.objects[_N.RIG]
    act = bpy.data.actions[name]
    if arm.animation_data is None:
        arm.animation_data_create()
    arm.animation_data.action = act
    try:
        if act.slots:
            arm.animation_data.action_slot = act.slots[0]
    except AttributeError:
        pass
    sc = bpy.context.scene
    if not sc.rl_keep_range:
        s, e = act.frame_range
        sc.frame_start, sc.frame_end = int(s), int(e)
        sc.frame_set(int(s))


# ---------------------------------------------------------------- mouth keyframes
def _fcurves(idb):
    ad = idb.animation_data
    if not ad or not ad.action:
        return []
    act = ad.action
    try:
        return list(act.fcurves)
    except AttributeError:
        from bpy_extras import anim_utils
        cb = anim_utils.action_get_channelbag_for_slot(act, ad.action_slot)
        return list(cb.fcurves) if cb else []


def _mouth_curve(sc):
    for fc in _fcurves(sc):
        if fc.data_path == 'rl_mouth':
            return fc
    return None


def clear_mouth_keys(sc, f0, f1):
    fc = _mouth_curve(sc)
    if not fc:
        return
    for kp in sorted([k for k in fc.keyframe_points if f0 <= k.co[0] <= f1], key=lambda k: -k.co[0]):
        fc.keyframe_points.remove(kp)


def key_mouth_sequence(sc, seq):
    """seq: list of (frame, mouth_index). Writes constant-interpolation keys."""
    for f, m in seq:
        sc.rl_mouth = m
        sc.keyframe_insert('rl_mouth', frame=f)
    fc = _mouth_curve(sc)
    if fc:
        for k in fc.keyframe_points:
            k.interpolation = 'CONSTANT'


def auto_talk(sc, f0, f1, seed=0):
    rnd = random.Random(seed)
    seq, f = [], f0
    while f < f1:
        if rnd.random() < 0.12:                      # short pause between phrases
            seq.append((f, 0)); f += rnd.randint(5, 9); continue
        seq.append((f, rnd.choice([1, 1, 2, 3, 4, 4, 5])))  # open-ish syllable
        f += rnd.randint(2, 4)
        seq.append((f, rnd.choice([0, 0, 4, 2])))           # partly close between syllables
        f += rnd.randint(1, 3)
    seq.append((f1, 0))
    clear_mouth_keys(sc, f0, f1)
    key_mouth_sequence(sc, seq)


def remove_voice_strips(sc):
    se = sc.sequence_editor
    if not se:
        return 0
    coll = se.strips if hasattr(se, 'strips') else se.sequences
    voices = [st for st in coll if st.type == 'SOUND' and st.name.startswith('voice')]
    for st in voices:
        coll.remove(st)
    return len(voices)


def clear_all_talking(sc):
    fc = _mouth_curve(sc)
    if fc:
        clear_mouth_keys(sc, -10**6, 10**6)
    n = remove_voice_strips(sc)
    sc.rl_mouth = 0
    set_mouth(0)
    return n


def lipsync_audio(sc, path, f0, add_strip=True):
    import aud, numpy as np
    snd = aud.Sound(bpy.path.abspath(path))
    rate = snd.specs[0]
    data = np.asarray(snd.data())
    mono = np.abs(data).mean(axis=1) if data.ndim > 1 else np.abs(data)
    fps = sc.render.fps / sc.render.fps_base
    hop = rate / fps
    nfr = int(len(mono) / hop)
    env = np.array([mono[int(i * hop):int((i + 1) * hop)].mean() if int((i + 1) * hop) > int(i * hop) else 0 for i in range(nfr)])
    if env.max() <= 0:
        return 0
    env = env / np.percentile(env, 95).clip(1e-6)
    rnd = random.Random(1)
    seq, last = [], None
    for i, v in enumerate(env):
        if v < 0.18:   m = 0
        elif v < 0.45: m = rnd.choice([4, 2, 3])
        else:          m = rnd.choice([1, 1, 5, 4])
        if m == last and m != 0 and i % 3 == 0:   # keep moving on long vowels
            m = 4 if m != 4 else 1
        if m != last:
            seq.append((f0 + i, m)); last = m
    seq.append((f0 + nfr, 0))
    clear_mouth_keys(sc, f0, f0 + nfr)
    key_mouth_sequence(sc, seq)
    if add_strip:
        remove_voice_strips(sc)          # only one voice at a time
        if not sc.sequence_editor:
            sc.sequence_editor_create()
        se = sc.sequence_editor
        coll = se.strips if hasattr(se, 'strips') else se.sequences
        coll.new_sound(name='voice', filepath=path, channel=1, frame_start=f0)
    if sc.frame_end < f0 + nfr:
        sc.frame_end = f0 + nfr
    return nfr


# ---------------------------------------------------------------- UI props
_MOOD_ITEMS = [(e, e, '') for e in MOODS]
_ACT_ITEMS = []
def _mood_items(self, ctx): return _MOOD_ITEMS
def _act_items(self, ctx):
    # Blender needs a persistent reference to dynamic enum items
    global _ACT_ITEMS
    items = [(a.name, a.name, '') for a in sorted(bpy.data.actions, key=lambda a: a.name)]
    if items != _ACT_ITEMS:
        _ACT_ITEMS = items
    return _ACT_ITEMS
def _upd_expr(self, ctx): set_expression(self.rl_expression)
def _upd_act(self, ctx): set_action(self.rl_action)
def _upd_mouth(self, ctx): set_mouth(self.rl_mouth)


class RL_OT_step(bpy.types.Operator):
    bl_idname = 'charlib.step'; bl_label = 'Step'
    kind: bpy.props.StringProperty()
    delta: bpy.props.IntProperty()

    def execute(self, ctx):
        sc = ctx.scene
        if self.kind == 'expr':
            items = MOODS
            i = items.index(sc.rl_expression) if sc.rl_expression in items else 0
            sc.rl_expression = items[(i + self.delta) % len(items)]
        else:
            items = [a.name for a in sorted(bpy.data.actions, key=lambda a: a.name)]
            i = items.index(sc.rl_action) if sc.rl_action in items else 0
            sc.rl_action = items[(i + self.delta) % len(items)]
        return {'FINISHED'}


class RL_OT_marker(bpy.types.Operator):
    bl_idname = 'charlib.add_expr_marker'; bl_label = 'Key Expression Here'
    bl_description = 'Add a timeline marker expr:<current expression> at the current frame'

    def execute(self, ctx):
        sc = ctx.scene
        sc.timeline_markers.new('expr:' + sc.rl_expression, frame=sc.frame_current)
        return {'FINISHED'}


class RL_OT_key_mouth(bpy.types.Operator):
    bl_idname = 'charlib.key_mouth'; bl_label = 'Key Mouth Here'
    bl_description = 'Keyframe the current mouth shape at the current frame'

    def execute(self, ctx):
        key_mouth_sequence(ctx.scene, [(ctx.scene.frame_current, ctx.scene.rl_mouth)])
        return {'FINISHED'}


class RL_OT_auto_talk(bpy.types.Operator):
    bl_idname = 'charlib.auto_talk'; bl_label = 'Auto Talk'
    bl_description = 'Fill the Talk From/To frames with random natural mouth movement'

    def execute(self, ctx):
        sc = ctx.scene
        auto_talk(sc, sc.rl_talk_from, sc.rl_talk_to, seed=sc.rl_talk_from)
        sc.frame_set(sc.frame_current)
        return {'FINISHED'}


class RL_OT_lipsync(bpy.types.Operator):
    bl_idname = 'charlib.lipsync'; bl_label = 'Lip-sync Audio'
    bl_description = 'Key the mouth to the loudness of the audio file, starting at Talk From, and add the audio to the timeline'

    def execute(self, ctx):
        sc = ctx.scene
        if not sc.rl_audio:
            self.report({'ERROR'}, 'Pick an audio file first'); return {'CANCELLED'}
        n = lipsync_audio(sc, sc.rl_audio, sc.rl_talk_from)
        self.report({'INFO'}, 'Lip-synced %d frames' % n)
        sc.frame_set(sc.frame_current)
        return {'FINISHED'}


class RL_OT_clear_talk(bpy.types.Operator):
    bl_idname = 'charlib.clear_talk'; bl_label = 'Clear Talking'
    bl_description = 'Remove mouth keys between Talk From and Talk To'

    def execute(self, ctx):
        sc = ctx.scene
        clear_mouth_keys(sc, sc.rl_talk_from, sc.rl_talk_to)
        sc.rl_mouth = 0
        return {'FINISHED'}


class RL_OT_remove_lipsync(bpy.types.Operator):
    bl_idname = 'charlib.remove_lipsync'; bl_label = 'Remove Lip-sync & Voice'
    bl_description = 'Delete ALL mouth keys and the voice audio from the timeline'

    def execute(self, ctx):
        n = clear_all_talking(ctx.scene)
        self.report({'INFO'}, 'Removed talking keys and %d voice clip(s)' % n)
        return {'FINISHED'}


class RL_PT_panel(bpy.types.Panel):
    bl_label = 'Character Library'; bl_space_type = 'VIEW_3D'; bl_region_type = 'UI'; bl_category = 'Character'

    def draw(self, ctx):
        sc = ctx.scene
        col = self.layout.column()
        col.label(text=_N.TITLE, icon='OUTLINER_OB_ARMATURE')
        col.label(text='Expression', icon='USER')
        r = col.row(align=True)
        op = r.operator('charlib.step', text='', icon='TRIA_LEFT'); op.kind = 'expr'; op.delta = -1
        r.prop(sc, 'rl_expression', text='')
        op = r.operator('charlib.step', text='', icon='TRIA_RIGHT'); op.kind = 'expr'; op.delta = 1
        col.operator('charlib.add_expr_marker', icon='MARKER_HLT')

        col.separator()
        box = col.box(); b = box.column()
        b.label(text='Talking (mouth layer)', icon='SPEAKER')
        r = b.row(align=True); r.prop(sc, 'rl_mouth', text='Mouth'); r.operator('charlib.key_mouth', text='', icon='KEY_HLT')
        b.label(text='0 = expression mouth, 1-5 = A I U E O')
        r = b.row(align=True); r.prop(sc, 'rl_talk_from', text='From'); r.prop(sc, 'rl_talk_to', text='To')
        r = b.row(align=True); r.operator('charlib.auto_talk', icon='OUTLINER_OB_SPEAKER'); r.operator('charlib.clear_talk', text='', icon='X')
        b.prop(sc, 'rl_audio', text='')
        b.operator('charlib.lipsync', icon='SOUND')
        b.operator('charlib.remove_lipsync', icon='TRASH')

        col.separator()
        col.label(text='Action', icon='ARMATURE_DATA')
        r = col.row(align=True)
        op = r.operator('charlib.step', text='', icon='TRIA_LEFT'); op.kind = 'act'; op.delta = -1
        r.prop(sc, 'rl_action', text='')
        op = r.operator('charlib.step', text='', icon='TRIA_RIGHT'); op.kind = 'act'; op.delta = 1
        col.prop(sc, 'rl_keep_range', text='Keep timeline length')
        r = col.row(align=True)
        r.operator('screen.animation_play', text='Play / Pause', icon='PLAY')
        r.operator('screen.frame_jump', text='', icon='REW').end = False


def _on_frame(scene, *a):
    ms = [m for m in scene.timeline_markers if m.name.startswith('expr:') and m.frame <= scene.frame_current]
    if ms:
        set_expression(max(ms, key=lambda m: m.frame).name[5:])
    fc = _mouth_curve(scene)
    if fc:
        set_mouth(round(fc.evaluate(scene.frame_current)))


CLASSES = (RL_OT_step, RL_OT_marker, RL_OT_key_mouth, RL_OT_auto_talk, RL_OT_lipsync, RL_OT_clear_talk, RL_OT_remove_lipsync, RL_PT_panel)


def register():
    for c in CLASSES:
        try:
            bpy.utils.unregister_class(getattr(bpy.types, c.__name__))
        except Exception:
            pass
        bpy.utils.register_class(c)
    S = bpy.types.Scene
    S.rl_expression = bpy.props.EnumProperty(name='Expression', items=_mood_items, update=_upd_expr)
    S.rl_action = bpy.props.EnumProperty(name='Action', items=_act_items, update=_upd_act)
    S.rl_mouth = bpy.props.IntProperty(name='Mouth', min=0, max=len(MOUTHS) - 1, update=_upd_mouth,
                                       description='0 = expression mouth, 1-5 = A I U E O')
    S.rl_talk_from = bpy.props.IntProperty(name='Talk From', default=0)
    S.rl_talk_to = bpy.props.IntProperty(name='Talk To', default=48)
    S.rl_audio = bpy.props.StringProperty(name='Voice audio', subtype='FILE_PATH')
    S.rl_keep_range = bpy.props.BoolProperty(name='Keep timeline length', default=False,
                                             description="Don't change the timeline length when switching action")
    for hl in (bpy.app.handlers.frame_change_pre, bpy.app.handlers.frame_change_post):
        for h in list(hl):
            if getattr(h, '__name__', '') == '_on_frame':
                hl.remove(h)
    bpy.app.handlers.frame_change_post.append(_on_frame)
    ensure_nodes()


register()
